/**
 * KRINT.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ActivityEntryDto { 
    id: string;
    action: string;
    target: string;
    instanceId?: string | null;
    engine?: string | null;
    details?: string | null;
    actorName?: string | null;
    createdAt: string;
}

