/**
 * KRINT.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BackupEntryDtoSizeBytes } from './backupEntryDtoSizeBytes';


export interface BackupEntryDto {
    id: string;
    instanceId: string;
    engine: string;
    engineVersion: string;
    fileName: string;
    sizeBytes: BackupEntryDtoSizeBytes;
    createdAt: string;
}

