/**
 * KRINT.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BulkUpdateRowEntryDto } from './bulkUpdateRowEntryDto';


export interface BulkUpdateRowsDto { 
    columns: Array<string>;
    updates: Array<BulkUpdateRowEntryDto>;
}

