/**
 * KRINT.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DatabaseInstanceDtoPort } from './databaseInstanceDtoPort';


export interface DatabaseInstanceDto { 
    id: string;
    engine: string;
    version: string;
    containerName: string;
    host: string;
    port: DatabaseInstanceDtoPort;
    username: string;
    databaseName: string;
    createdAt: string;
}

