/**
 * KRINT.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DashboardStatsDtoTotalInstances } from './dashboardStatsDtoTotalInstances';


export interface DiscoveredContainerDto { 
    containerId: string;
    containerName: string;
    engine: string;
    image: string;
    version: string;
    host: string;
    port: DashboardStatsDtoTotalInstances;
    username: string;
    password?: string | null;
    databaseName: string;
    state: string;
}

