/**
 * KRINT.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DashboardStatsDtoTotalInstances } from './dashboardStatsDtoTotalInstances';


export interface DiscoveredContainerDto { 
    containerId: string;
    containerName: string;
    engine: string;
    image: string;
    version: string;
    host: string;
    port: DashboardStatsDtoTotalInstances;
    username: string;
    /**
     * Whether the container's environment carries a password KRINT can read when the container is adopted. The password itself is never listed.
     */
    passwordAvailable: boolean;
    databaseName: string;
    state: string;
    composeProject?: string | null;
    composeService?: string | null;
    composeFilePath?: string | null;
}

