/**
 * KRINT.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EngineCapabilitiesDto { 
    databaseTerm: string;
    tableTerm: string;
    rowTerm: string;
    supportsListDatabases: boolean;
    supportsCreateDatabase: boolean;
    supportsDropDatabase: boolean;
    supportsListTables: boolean;
    supportsDropTable: boolean;
    supportsRowRead: boolean;
    supportsRowInsert: boolean;
    supportsRowEdit: boolean;
    supportsRowDelete: boolean;
    supportsUsers: boolean;
    supportsBackup: boolean;
}

