/**
 * KRINT.API | v1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DashboardStatsDtoTotalInstances } from './dashboardStatsDtoTotalInstances';


export interface MigrationRequestDto {
    sourceContainerId: string;
    sourceHost: string;
    sourcePort: DashboardStatsDtoTotalInstances;
    sourceUsername: string;
    sourcePassword: string;
    sourceDatabaseName: string;
    sourceEngine: string;
    targetEngine: string;
    targetVersion: string;
    targetDisplayName: string;
    composeProject?: string | null;
    composeService?: string | null;
    composeFilePath?: string | null;
}
