/**
 * KRINT.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NodeDto { 
    connectionId: string;
    name: string;
    machineName: string;
    os: string;
    dockerVersion: string;
    online: boolean;
    connectedAt: string;
    lastSeenAt: string;
}

