/**
 * KRINT.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProvisionedDatabaseDtoPort } from './provisionedDatabaseDtoPort';


export interface ProvisionedDatabaseDto { 
    id: string;
    engine: string;
    version: string;
    containerName: string;
    host: string;
    port: ProvisionedDatabaseDtoPort;
    username: string;
    databaseName: string;
    password: string;
    connectionString: string;
    createdAt: string;
}

