/**
 * KRINT.API | v1
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProvisionResultDto } from './provisionResultDto';


/**
 * One event of a streamed provision: a running step, the finished result, or the failure.
 */
export interface ProvisionProgressDto {
    /**
     * \"running\", \"done\" or \"failed\".
     */
    status: string;
    message: string;
    result?: ProvisionResultDto | null;
    error?: string | null;
}

