/**
 * KRINT.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProvisionUserSpec } from './provisionUserSpec';


export interface ProvisionRequestDto { 
    engine: string;
    version: string;
    displayName: string;
    defaultDatabaseName?: string | null;
    databases?: Array<string>;
    users?: Array<ProvisionUserSpec>;
    plugins?: Array<string>;
}

