/**
 * KRINT.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DashboardStatsDtoTotalInstances } from './dashboardStatsDtoTotalInstances';


export interface RegisterExternalDatabaseDto { 
    engine: string;
    version: string;
    displayName: string;
    host: string;
    port: DashboardStatsDtoTotalInstances;
    username: string;
    password: string;
    databaseName: string;
    containerId?: string | null;
    containerName?: string | null;
}

