/**
 * KRINT.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DashboardStatsDtoTotalInstances } from './dashboardStatsDtoTotalInstances';
import { RunQueryColumnDto } from './runQueryColumnDto';
import { BackupEntryDtoSizeBytes } from './backupEntryDtoSizeBytes';


export interface RunQueryResultDto { 
    columns: Array<RunQueryColumnDto>;
    rows: Array<Array<string>>;
    rowsAffected: DashboardStatsDtoTotalInstances;
    elapsedMs: BackupEntryDtoSizeBytes;
    truncated: boolean;
}

