/**
 * KRINT.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProblemDetailsStatus } from './problemDetailsStatus';


export interface RunQueryRequestDto { 
    database: string;
    sql: string;
    rowLimit?: ProblemDetailsStatus | null;
}

