/**
 * KRINT.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PortRangeDto } from './portRangeDto';
import { SupportedDatabaseDto } from './supportedDatabaseDto';


export interface SettingsDto { 
    portRanges: Array<PortRangeDto>;
    supportedEngines: Array<SupportedDatabaseDto>;
    vaultMasterKeyConfigured: boolean;
}

