/**
 * KRINT.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnginePluginDto } from './enginePluginDto';
import { EngineCapabilitiesDto } from './engineCapabilitiesDto';


export interface SupportedDatabaseDto { 
    key: string;
    displayName: string;
    image: string;
    versions: Array<string>;
    capabilities: EngineCapabilitiesDto;
    plugins?: Array<EnginePluginDto>;
}

