/**
 * KRINT.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TableRowsDtoTotalCount } from './tableRowsDtoTotalCount';
import { ColumnInfoDto } from './columnInfoDto';


export interface TableRowsDto { 
    columns: Array<string>;
    rows: Array<Array<string>>;
    totalCount?: TableRowsDtoTotalCount | null;
    columnInfos?: Array<ColumnInfoDto> | null;
}

