/**
 * KRINT.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VectorPointDtoVectorInner } from './vectorPointDtoVectorInner';


export interface VectorPointDto { 
    id: string;
    vector: Array<VectorPointDtoVectorInner>;
    payload: string;
}

