/**
 * KRINT.API | v1
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DashboardStatsDtoTotalInstances } from './dashboardStatsDtoTotalInstances';
import { VectorPointDto } from './vectorPointDto';


export interface VectorClusterDto { 
    dimensions: DashboardStatsDtoTotalInstances;
    points: Array<VectorPointDto>;
}

